name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 17.x
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: npm install (backend)
        run: cd backend && npm install

      - name: Check style (backend)
        run: cd backend && npm run check-format
        
      - name: npm install (frontend)
        run: cd frontend && npm install

      - name: Check style (frontend)
        run: cd frontend && npm run check-format

  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 17.x
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: npm install
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build