name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install
        run: npm install

      - name: Check style
        run: npm run check-format

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build